### ISSUE TITLE
Burricos stack trace 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Burricos#3]
2015-01-06 20:42:47 [ERROR] Could not pass event InventoryClickEvent to Burricos v1.2                                                 │·········································
org.bukkit.event.EventException                                                                                                       │·········································
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9│·········································
b]                                                                                                                                    │·········································
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b$│·········································
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec$│·········································
b]                                                                                                                                    │·········································
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec$│·········································
b]                                                                                                                                    │·········································
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:1431) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b$│·········································
        at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.a(SourceFile:32) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]      │·········································
        at net.minecraft.server.v1_7_R4.PacketPlayInWindowClick.handle(SourceFile:10) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b] │·········································
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]     │·········································
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]  │·········································
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]   │·········································
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]   │·········································
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]   │·········································
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b] │·········································
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]   │·········································
Caused by: java.lang.NullPointerException                                                                                             │·········································
        at com.gipsyking.Burricos.Burricos.isZipItem(Burricos.java:317) ~[?:?]                                                        │·········································
        at com.gipsyking.Burricos.Burricos.inventoryClickEvent(Burricos.java:153) ~[?:?]                                              │·········································
        at sun.reflect.GeneratedMethodAccessor193.invoke(Unknown Source) ~[?:?]                                                       │·········································
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_65]                        │·········································
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_65]                                                             │·········································
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec$│·········································
b]                                                                                                                                    │·········································
        ... 13 more

**Comment by rourke750** [comment]
@gipsy-king

**Comment by gipsy-king** [comment]
Thanks

**Comment by rourke750** [comment]
Any news on this?

**Comment by ttk2** [comment]
I don't remember seeing it again
